project:
  type: website
  output-dir: docs

website:
  title: "Patrick Coyle"
  site-url: https://patrickcoyle.github.io/quarto_blog_coyle
  description: "This is Patrick Coyle's personal blog."
  sidebar:
    style: "floating"
    alignment: left
    border: true
    title: "Patrick Coyle"
    subtitle: "Statistician"
    search: true
    contents:
      section: "Blog Posts"
      href: blog.qmd
      contents: posts/**/*.qmd
    collapse-level: 1

format:
  html:
    page-layout: full
    theme: flatly
    css: styles.css

editor: visual

