project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!dev/"

website:
  title: "Patrick Coyle"
  site-url: https://patrickcoyle.github.io/personal
  description: "This is Patrick Coyle's personal blog."
  navbar:
    title: "Patrick Coyle"
    subtitle: "Statistician"
    search: true
    right:
      - text: "Blog"
        href: blog.qmd
      # - text: "RSS Reader" ## RSS feeds for Posit blogs appear to be deactivated as of October 2025
      #   href: rss_reader.qmd

format:
  html:
    page-layout: full
    theme: flatly
    css: styles.css

editor: visual

