project:
  type: website
  output-dir: docs

website:
  title: "Patrick Coyle"
  site-url: https://patrickcoyle.github.io/quarto_blog_coyle
  description: "This is Patrick Coyle's personal blog."
  # navbar:
  #   left:
  #     - text: Blog
  #       href: blog.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

