project:
  type: website
  output-dir: docs

website:
  title: "Patrick Coyle"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PatrickCoyle
      - icon: twitter
        href: https://twitter.com/Patrick78941150
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

