  graph LR
  E1 --> ES1
  E8 --> ES1
  E4 --> ES4
  E5 --> ES4
  E2 --> ES2
  E7 --> ES2
  E3 --> ES3
  E6 --> ES3
  ES1 --> EF1
  ES4 --> EF1
  ES2 --> EF2
  ES3 --> EF2
  EF1 --> EC
  EF2 --> EC
  EC --> C
  W1 --> WS1
  W8 --> WS1
  W4 --> WS4
  W5 --> WS4
  W2 --> WS2
  W7 --> WS2
  W3 --> WS3
  W6 --> WS3
  WS1 --> WF1
  WS4 --> WF1
  WS2 --> WF2
  WS3 --> WF2
  WF1 --> WC
  WF2 --> WC
  WC --> C