name: Render Quarto Project

on:
  push:
    branches: [ main ]  # Change branch name as needed

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render project
        uses: quarto-dev/quarto-actions/render@v2  # Use the render action
