name: Render Quarto Project

on:
  push:
    branches: [ main ]  # Change branch name as needed

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render project
        uses: quarto-dev/quarto-actions/render@v2  # Use the render action
